import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
// contexts
import { ChatProvider } from '@/app/contexts/ChatContext';
import { PlusChatProvider } from '@/app/contexts/PlusChatContext';
// styles
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

/**
 * レイアウト
 * @param children 子要素
 * @returns JSX.Element
 */
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body>
                <ClerkProvider afterSignOutUrl="/">
                    <PlusChatProvider>
                        <ChatProvider>{children}</ChatProvider>
                    </PlusChatProvider>
                </ClerkProvider>
            </body>
        </html>
    );
}
